; gta-reversed headless configuration
; All splashes/videos/menus skipped, auto-loads first available save game

[FastLoader]
Enable=1
SaveGameToLoad=-1
SkipSaveGameLoadKey=0
NoEAX=1
NoNVidia=1
NoLogo=1
NoTitleOrIntro=1
NoCopyright=1
NoFading=1
NoLoadScreen=1
NoLoadBar=0
NoLoadingTune=1
NoDbgLogScreens=0
RenderAtAllTimes=1
ScreenChangeTime=0
